//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrawlerIO.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Elements
    {
        public int Id { get; set; }
        public Nullable<int> UrlId { get; set; }
        public string ElementType { get; set; }
        public string TagName { get; set; }
        public string TagAsJson { get; set; }
        public Nullable<bool> Navigatable { get; set; }
        public string NavigateURL { get; set; }
        public string TagHash { get; set; }
    }
}
